sudo: required
services:
  - docker

before_install:
  - docker build -t rakeshcheekatimala/react-boiler-plate -f Dockerfile.dev .

script:
  - docker run rakeshcheekatimala/react-boiler-plate npm run test -- --coverage
